// Copyright Epic Games, Inc. All Rights Reserved.

#include "FLECS.h"
#include "FLECS/Public/FLECS.h"
#include "flecs.h"

#pragma comment(linker, "/export:ECS_PAIR")
#pragma comment(linker, "/export:ECS_AUTO_OVERRIDE")
#pragma comment(linker, "/export:ECS_TOGGLE")
#pragma comment(linker, "/export:ECS_VALUE_PAIR")
#pragma comment(linker, "/export:FLECS_IDEcsComponentID_")
#pragma comment(linker, "/export:FLECS_IDEcsIdentifierID_")
#pragma comment(linker, "/export:FLECS_IDEcsPolyID_")
#pragma comment(linker, "/export:FLECS_IDEcsParentID_")
#pragma comment(linker, "/export:FLECS_IDEcsTreeSpawnerID_")
#pragma comment(linker, "/export:FLECS_IDEcsDefaultChildComponentID_")
#pragma comment(linker, "/export:FLECS_IDEcsTickSourceID_")
#pragma comment(linker, "/export:ecs_os_init")
#pragma comment(linker, "/export:flecs_poly_claim_")
#pragma comment(linker, "/export:flecs_poly_release_")
#pragma comment(linker, "/export:ecs_fini")
#pragma comment(linker, "/export:ecs_stage_free")
#pragma comment(linker, "/export:ecs_stage_get_id")
#pragma comment(linker, "/export:ecs_entity_init")
#pragma comment(linker, "/export:ecs_delete")
#pragma comment(linker, "/export:ecs_add_id")
#pragma comment(linker, "/export:ecs_is_valid")
#pragma comment(linker, "/export:ecs_is_alive")
#pragma comment(linker, "/export:flecs_component_ids_index_get")
#pragma comment(linker, "/export:flecs_component_ids_get_alive")
#pragma comment(linker, "/export:flecs_defer_end")
#pragma comment(linker, "/export:ecs_remove_id")
#pragma comment(linker, "/export:ecs_get_id")
#pragma comment(linker, "/export:ecs_get_mut_id")
#pragma comment(linker, "/export:ecs_modified_id")
#pragma comment(linker, "/export:ecs_has_id")
#pragma comment(linker, "/export:ecs_set_hooks_id")
#pragma comment(linker, "/export:ecs_query_init")
#pragma comment(linker, "/export:ecs_query_fini")
#pragma comment(linker, "/export:ecs_query_iter")
#pragma comment(linker, "/export:ecs_query_next")
#pragma comment(linker, "/export:ecs_field_w_size")
#pragma comment(linker, "/export:ecs_field_at_w_size")
#pragma comment(linker, "/export:ecs_cpp_get_type_name")
#pragma comment(linker, "/export:ecs_cpp_component_register")
#pragma comment(linker, "/export:ecs_cpp_set")
#pragma comment(linker, "/export:ecs_cpp_new")
#pragma comment(linker, "/export:ecs_get_parent")
#pragma comment(linker, "/export:ecs_get_world")
#pragma comment(linker, "/export:ecs_emit")
#pragma comment(linker, "/export:ecs_enqueue")
#pragma comment(linker, "/export:ecs_observer_init")
#pragma comment(linker, "/export:ecs_observer_update")
#pragma comment(linker, "/export:ecs_observer_get")
#pragma comment(linker, "/export:ecs_os_api")
#pragma comment(linker, "/export:FLECS_IDEcsTimerID_")
#pragma comment(linker, "/export:FLECS_IDEcsRateFilterID_")
#pragma comment(linker, "/export:EcsParentDepth")
#pragma comment(linker, "/export:EcsQuery")
#pragma comment(linker, "/export:EcsObserver")
#pragma comment(linker, "/export:EcsSystem")
#pragma comment(linker, "/export:EcsFlecs")
#pragma comment(linker, "/export:EcsFlecsCore")
#pragma comment(linker, "/export:EcsWorld")
#pragma comment(linker, "/export:EcsWildcard")
#pragma comment(linker, "/export:EcsAny")
#pragma comment(linker, "/export:EcsThis")
#pragma comment(linker, "/export:EcsVariable")
#pragma comment(linker, "/export:EcsTransitive")
#pragma comment(linker, "/export:EcsReflexive")
#pragma comment(linker, "/export:EcsFinal")
#pragma comment(linker, "/export:EcsInheritable")
#pragma comment(linker, "/export:EcsOnInstantiate")
#pragma comment(linker, "/export:EcsOverride")
#pragma comment(linker, "/export:EcsInherit")
#pragma comment(linker, "/export:EcsDontInherit")
#pragma comment(linker, "/export:EcsSymmetric")
#pragma comment(linker, "/export:EcsExclusive")
#pragma comment(linker, "/export:EcsAcyclic")
#pragma comment(linker, "/export:EcsTraversable")
#pragma comment(linker, "/export:EcsWith")
#pragma comment(linker, "/export:EcsOneOf")
#pragma comment(linker, "/export:EcsCanToggle")
#pragma comment(linker, "/export:EcsTrait")
#pragma comment(linker, "/export:EcsRelationship")
#pragma comment(linker, "/export:EcsTarget")
#pragma comment(linker, "/export:EcsPairIsTag")
#pragma comment(linker, "/export:EcsName")
#pragma comment(linker, "/export:EcsSymbol")
#pragma comment(linker, "/export:EcsAlias")
#pragma comment(linker, "/export:EcsChildOf")
#pragma comment(linker, "/export:EcsIsA")
#pragma comment(linker, "/export:EcsDependsOn")
#pragma comment(linker, "/export:EcsSlotOf")
#pragma comment(linker, "/export:EcsOrderedChildren")
#pragma comment(linker, "/export:EcsModule")
#pragma comment(linker, "/export:EcsPrefab")
#pragma comment(linker, "/export:EcsDisabled")
#pragma comment(linker, "/export:EcsNotQueryable")
#pragma comment(linker, "/export:EcsOnAdd")
#pragma comment(linker, "/export:EcsOnRemove")
#pragma comment(linker, "/export:EcsOnSet")
#pragma comment(linker, "/export:EcsMonitor")
#pragma comment(linker, "/export:EcsOnTableCreate")
#pragma comment(linker, "/export:EcsOnTableDelete")
#pragma comment(linker, "/export:EcsOnDelete")
#pragma comment(linker, "/export:EcsOnDeleteTarget")
#pragma comment(linker, "/export:EcsRemove")
#pragma comment(linker, "/export:EcsDelete")
#pragma comment(linker, "/export:EcsPanic")
#pragma comment(linker, "/export:EcsSingleton")
#pragma comment(linker, "/export:EcsSparse")
#pragma comment(linker, "/export:EcsDontFragment")
#pragma comment(linker, "/export:EcsPredEq")
#pragma comment(linker, "/export:EcsPredMatch")
#pragma comment(linker, "/export:EcsPredLookup")
#pragma comment(linker, "/export:EcsScopeOpen")
#pragma comment(linker, "/export:EcsScopeClose")
#pragma comment(linker, "/export:EcsEmpty")
#pragma comment(linker, "/export:FLECS_IDEcsPipelineID_")
#pragma comment(linker, "/export:EcsOnStart")
#pragma comment(linker, "/export:EcsPreFrame")
#pragma comment(linker, "/export:EcsOnLoad")
#pragma comment(linker, "/export:EcsPostLoad")
#pragma comment(linker, "/export:EcsPreUpdate")
#pragma comment(linker, "/export:EcsOnUpdate")
#pragma comment(linker, "/export:EcsOnValidate")
#pragma comment(linker, "/export:EcsPostUpdate")
#pragma comment(linker, "/export:EcsPreStore")
#pragma comment(linker, "/export:EcsOnStore")
#pragma comment(linker, "/export:EcsPostFrame")
#pragma comment(linker, "/export:EcsPhase")
#pragma comment(linker, "/export:EcsConstant")
#pragma comment(linker, "/export:FLECS_IDEcsDocDescriptionID_")
#pragma comment(linker, "/export:EcsDocUuid")
#pragma comment(linker, "/export:EcsDocBrief")
#pragma comment(linker, "/export:EcsDocDetail")
#pragma comment(linker, "/export:EcsDocLink")
#pragma comment(linker, "/export:EcsDocColor")
#pragma comment(linker, "/export:FLECS_IDEcsTypeID_")
#pragma comment(linker, "/export:FLECS_IDEcsTypeSerializerID_")
#pragma comment(linker, "/export:FLECS_IDEcsPrimitiveID_")
#pragma comment(linker, "/export:FLECS_IDEcsEnumID_")
#pragma comment(linker, "/export:FLECS_IDEcsBitmaskID_")
#pragma comment(linker, "/export:FLECS_IDEcsConstantsID_")
#pragma comment(linker, "/export:FLECS_IDEcsMemberID_")
#pragma comment(linker, "/export:FLECS_IDEcsMemberRangesID_")
#pragma comment(linker, "/export:FLECS_IDEcsStructID_")
#pragma comment(linker, "/export:FLECS_IDEcsArrayID_")
#pragma comment(linker, "/export:FLECS_IDEcsVectorID_")
#pragma comment(linker, "/export:FLECS_IDEcsOpaqueID_")
#pragma comment(linker, "/export:FLECS_IDEcsUnitID_")
#pragma comment(linker, "/export:FLECS_IDEcsUnitPrefixID_")
#pragma comment(linker, "/export:EcsQuantity")
#pragma comment(linker, "/export:FLECS_IDecs_bool_tID_")
#pragma comment(linker, "/export:FLECS_IDecs_char_tID_")
#pragma comment(linker, "/export:FLECS_IDecs_byte_tID_")
#pragma comment(linker, "/export:FLECS_IDecs_u8_tID_")
#pragma comment(linker, "/export:FLECS_IDecs_u16_tID_")
#pragma comment(linker, "/export:FLECS_IDecs_u32_tID_")
#pragma comment(linker, "/export:FLECS_IDecs_u64_tID_")
#pragma comment(linker, "/export:FLECS_IDecs_uptr_tID_")
#pragma comment(linker, "/export:FLECS_IDecs_i8_tID_")
#pragma comment(linker, "/export:FLECS_IDecs_i16_tID_")
#pragma comment(linker, "/export:FLECS_IDecs_i32_tID_")
#pragma comment(linker, "/export:FLECS_IDecs_i64_tID_")
#pragma comment(linker, "/export:FLECS_IDecs_iptr_tID_")
#pragma comment(linker, "/export:FLECS_IDecs_f32_tID_")
#pragma comment(linker, "/export:FLECS_IDecs_f64_tID_")
#pragma comment(linker, "/export:FLECS_IDecs_string_tID_")
#pragma comment(linker, "/export:FLECS_IDecs_entity_tID_")
#pragma comment(linker, "/export:FLECS_IDecs_id_tID_")
#pragma comment(linker, "/export:FLECS_IDEcsRestID_")

#define LOCTEXT_NAMESPACE "FFLECSModule"

void FFLECSModule::StartupModule()
{
	// This code will execute after your module is loaded into memory; the exact timing is specified in the .uplugin file per-module
}

void FFLECSModule::ShutdownModule()
{
	// This function may be called during shutdown to clean up your module.  For modules that support dynamic reloading,
	// we call this function before unloading the module.
}

#undef LOCTEXT_NAMESPACE
	
IMPLEMENT_MODULE(FFLECSModule, FLECS)
